const productos = [
  { id: 1, titulo: "Quantum Play X1", desc: "Experimenta el poder sin igual con la QuantumPlay X1. Equipada con tecnología de vanguardia, esta consola ofrece juegos en 8K, HDR dinámico y un rendimiento excepcional. Su diseño elegante y su interfaz intuitiva hacen que la QuantumPlay X1 sea la elección definitiva para los verdaderos amantes de los videojuegos.", precio: 700, categoria: "consolas", stock: 10, imagen:'consola1'},
  { id: 2, titulo: "QuantumX Titan Gaming Rig", desc: "Sumérgete en el rendimiento legendario con la QuantumX Titan Gaming Rig, una PC diseñada para llevar tus experiencias de juego a niveles épicos. Equipada con un procesador de última generación, tarjeta gráfica de alto rendimiento y una refrigeración avanzada, esta máquina es la encarnación de la potencia sin límites. Con iluminación personalizable, almacenamiento ultrarrápido y capacidades de transmisión en vivo.", precio: 950, categoria: "computadoras", stock: 3, imagen:'pc1'},
  { id: 3, titulo: "NeoStation", desc: "Descubre una nueva dimensión de juego con la NovaTech NeoStation. Desde gráficos de alta fidelidad hasta un sistema de sonido envolvente, cada detalle ha sido cuidadosamente diseñado para brindar una experiencia de juego completa. Su conectividad avanzada y capacidades de transmisión hacen que compartir tus momentos épicos sea más fácil que nunca", precio: 650, categoria: "consolas", stock: 6, imagen:'consola2'},
  { id: 4, titulo: " SonicWave Pro-X Gaming Headset", desc: "Sumérgete en la acción con los auriculares SonicWave Pro-X, diseñados para llevar tu experiencia de juego a un nuevo nivel de inmersión. Con sonido envolvente 7.1, micrófono con cancelación de ruido y luces LED personalizables, estos auriculares ofrecen un rendimiento excepcional y comodidad duradera. Domina cada detalle del juego con claridad cristalina y vive la emoción como nunca antes con SonicWave Pro-X Gaming Headset", precio: 60, categoria: "accesorios", stock: 9, imagen:'accesorio1'},
  { id: 5, titulo: "Nexus Control Ultimate GamePad", desc: "Experimenta el poder de control total con el NexusControl Ultimate GamePad. Diseñado para jugadores exigentes, este mando para consola ofrece una respuesta precisa, botones programables y un diseño ergonómico que se adapta perfectamente a tus manos. La conectividad inalámbrica de última generación garantiza una experiencia sin retardos.", precio: 70, categoria: "accesorios", stock: 11, imagen:'accesorio2'},
  { id: 6, titulo: "RetroVibe Classic Console", desc: " La Classic Console de RetroVibe rinde homenaje a los juegos legendarios que han definido la historia de los videojuegos. Con una estética inspirada en las consolas clásicas y una selección de juegos atemporales, esta consola es el sueño hecho realidad para aquellos que aprecian la simplicidad y la magia de los juegos de antaño", precio: 600, categoria: "consolas", stock: 19, imagen:'consola3'}
]

export default productos